//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses()
        {
            this.StudentNotes = new HashSet<StudentNotes>();
        }
    
        public int c_id { get; set; }
        public string c_name { get; set; }
        public int c_credit { get; set; }
        public byte dep_id { get; set; }
        public string c_semester_season { get; set; }
        public byte c_level { get; set; }
        public byte session { get; set; }
        public Nullable<int> inst_id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Instructors Instructors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentNotes> StudentNotes { get; set; }
    }
}
